### ISSUE TITLE
Any idea where to file an issue for xmlstarlet cli tool?

### ISSUE THREAD

**Issue by wlad** [dimitern/xmlstarlet#148]
I'd like to report an issue with the original cli tool (which can be install via apt).

It does not report an error when trying to modify/update or delet an xpath that does not exist. I'd expect this to fail.

Any idea where to address the  issue?

Cheers

**Comment by wlad** [comment]
I think I found the right place --> https://sourceforge.net/p/xmlstar/bugs/ (?)

But it requires registration/login etc. 

They may consider moving to Github, Bitbucket or at least Gitlab to get more exposure and contribution(?)
Who is registered on Sourceforge nowadays? 🙄

**Comment by dimitern** [comment]
@wlad Hey, thank you for reporting this, but since it concerns the original sources, I'll close it. Please, feel to open another if you're having problems with xmlstarlet  CFFI!
